package:
  name: deepgraph
  version: "0.0.8"

build:
  number: 0

source:
  # fn: DeepGraph-0.0.8.tar.gz
  # url: https://pypi.python.org/packages/source/D/DeepGraph/DeepGraph-0.0.8.tar.gz
  # md5: 48f75bccb12b5ce365a9cad522e59edb
  # git_url: https://github.com/deepgraph/deepgraph.git
  # git_rev: master  # 0.0.8
  path: ../dist/DeepGraph-0.0.8

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
  run:
    - python
    - numpy
    - pandas

test:
  files:
    - ../tests/test_DeepGraph.py
    - ../tests/test_CreateEdges.py
  requires:
    - deepgraph
    - pytest
    - numpy
    - pandas
    - scipy
    - networkx
    # - tables
  imports:
    - deepgraph
    - pytest
  commands:
    # - pip install tables
    - conda install -y -p $PREFIX -c anaconda pytables
    # - conda install -y -f --use-local deepgraph  # seems hackish, but works..
    # - cd ../work/tests  # seems hackish, but works..
    - cd $PREFIX/../tests/
    - py.test -v

about:
  summary: >
    DeepGraph is a scalable, general-purpose data analysis package. It
    implements a network representation based on pandas DataFrames and
    provides methods to construct, partition and plot graphs, to interface
    with popular network packages and more.
  home: https://github.com/deepgraph/deepgraph
  license: BSD

